name: Hive-build-workflow
on: 
  push:
    branches:
      - 'master'
jobs:
  build-Ranger:
    name: Build Hive-3.1.3 with Hadoop 3.3.1 and HBase 2.4.14
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images 
    steps:
      - name: Checkout branche march-rel/release-3.1.3
        uses: actions/checkout@v3
        with:
          ref: master #march-rel/release-3.1.3
      - name: setup maven
        uses: s4u/maven-settings-action@v2.7.0
        with:
          mirrors: '[{"id": "central", "name": "central", "mirrorOf": "central", "url": "https://repo.maven.apache.org/maven2"}, {"id": "aliyun", "name": "aliyun", "mirrorOf": "*", "url": "https://maven.aliyun.com/repository/spring-plugin"}]'
          #mirrors: '[{"id": "cloudera", "name": "Cloudera_Repo", "mirrorOf": "*", "url": "https://repository.cloudera.com/artifactory/repo/"}]'
      - name: find Maven setting.xml files
        run: sudo find ./ -name 'settings.xml'
      - name: cat  Maven setting.xml files
        run: cat /home/runner/.m2/settings.xml
      - name: install openjdk-8-jdk
        run: sudo apt-get -y install openjdk-8-jdk
      - name: build Hive-3.1.3
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: mvn package -Pdist -DskipTests -Dmaven.javadoc.skip=true

        