name: Hive-build-workflow
on: 
  push:
    branches:
      - 'master'
jobs:
  build-Ranger:
    name: Build Hive-3.1.3 with Hadoop 3.3.1 and HBase 2.4.14
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images 
    steps:
      - name: Checkout branche march-rel/release-3.1.3
        uses: actions/checkout@v3
        with:
          ref: march-rel/release-3.1.3
      - name: install openjdk-8-jdk
        run: sudo apt-get -y install openjdk-8-jdk
      - name: build Hive-3.1.3
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        #run: mvn -DskipJSTests -DskipTests clean compile package install
        run: mvn -e -X package -Pdist -DskipTests -Dmaven.javadoc.skip=true
      - name: check TAR files
        run: ls -alhR ./packaging/target/