name: Hive-build-workflow
on: 
  push:
    branches:
      - 'master'
jobs:
  build-Ranger:
    name: Build Hive-3.1.3 with Hadoop 3.3.1 and HBase 2.4.14
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images 
    steps:
      - name: Checkout branche march-rel/release-3.1.3
        uses: actions/checkout@v3
        with:
          ref: march-rel/release-3.1.3
      - name: setup maven
        uses: s4u/maven-settings-action@v2.7.0
        with:
          mirrors: '[{"id": "aliyunmaven", "name": "aliyunmaven", "mirrorOf": "*", "url": "https://maven.aliyun.com/repository/spring-plugin"}, {"id": "repo2", "name": "Mirror from Maven Repo2", "mirrorOf": "central", "url": "https://repo.spring.io/plugins-release/"}]'
      #- name: install openjdk-8-jdk
      #  run: sudo apt-get -y install openjdk-8-jdk
      #- name: build Hive-3.1.3
      #  env:
      #    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      #  #run: mvn -DskipJSTests -DskipTests clean compile package install
      #  run: mvn -e -X package -Pdist -DskipTests -Dmaven.javadoc.skip=true
      - name: check Maven setting.xml files
        run: sudo find / -type d -name '.m2'